#!/usr/bin/env python3
"""Generate tiles.c from tiles.png for the GBA MIDI UI."""

import struct
import sys
import zlib


START_TILE = 31
END_TILE = 142


def read_png_indexed(path):
    with open(path, "rb") as f:
        data = f.read()

    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG file")

    pos = 8
    width = height = bit_depth = color_type = None
    palette = []
    idat = bytearray()

    while pos < len(data):
        if pos + 8 > len(data):
            raise ValueError("truncated PNG chunk header")
        size = struct.unpack(">I", data[pos:pos + 4])[0]
        chunk_type = data[pos + 4:pos + 8]
        chunk_data = data[pos + 8:pos + 8 + size]
        pos += 12 + size

        if chunk_type == b"IHDR":
            width, height, bit_depth, color_type, _, _, _ = struct.unpack(">IIBBBBB", chunk_data)
        elif chunk_type == b"PLTE":
            palette = [tuple(chunk_data[i:i + 3]) for i in range(0, len(chunk_data), 3)]
        elif chunk_type == b"IDAT":
            idat.extend(chunk_data)
        elif chunk_type == b"IEND":
            break

    if color_type != 3 or bit_depth not in (1, 2, 4, 8):
        raise ValueError("expected an indexed PNG")

    raw = zlib.decompress(bytes(idat))
    packed_stride = (width * bit_depth + 7) // 8
    rows = []
    prev = [0] * packed_stride
    p = 0
    for _ in range(height):
        filter_type = raw[p]
        p += 1
        row = list(raw[p:p + packed_stride])
        p += packed_stride

        if filter_type == 1:
            for i in range(packed_stride):
                left = row[i - 1] if i else 0
                row[i] = (row[i] + left) & 0xFF
        elif filter_type == 2:
            for i in range(packed_stride):
                row[i] = (row[i] + prev[i]) & 0xFF
        elif filter_type == 3:
            for i in range(packed_stride):
                left = row[i - 1] if i else 0
                row[i] = (row[i] + ((left + prev[i]) >> 1)) & 0xFF
        elif filter_type == 4:
            for i in range(packed_stride):
                left = row[i - 1] if i else 0
                up = prev[i]
                up_left = prev[i - 1] if i else 0
                pred = paeth(left, up, up_left)
                row[i] = (row[i] + pred) & 0xFF
        elif filter_type != 0:
            raise ValueError(f"unsupported PNG filter {filter_type}")

        rows.append(unpack_indexed_row(row, width, bit_depth))
        prev = row

    return width, height, palette, rows


def unpack_indexed_row(row, width, bit_depth):
    if bit_depth == 8:
        return row[:width]

    mask = (1 << bit_depth) - 1
    out = []
    for byte in row:
        for shift in range(8 - bit_depth, -1, -bit_depth):
            out.append((byte >> shift) & mask)
            if len(out) == width:
                return out
    return out


def paeth(a, b, c):
    p = a + b - c
    pa = abs(p - a)
    pb = abs(p - b)
    pc = abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


tile_data_rle = []
pending = []
repeating = False


def add_nibble(n):
    global pending, repeating
    if len(pending) == 0:
        pending = [n]
    elif len(pending) == 1:
        repeating = pending[0] == n
        pending.append(n)
    elif repeating:
        if len(pending) == 8 or n != pending[0]:
            tile_data_rle.append(len(pending))
            tile_data_rle.append(pending[0])
            pending = [n]
        else:
            pending.append(n)
    else:
        if len(pending) == 7 or n == pending[-1]:
            tile_data_rle.append(len(pending) + 8)
            tile_data_rle.extend(pending)
            pending = [n]
        else:
            pending.append(n)


def gen_tile(rows, xoff, yoff):
    for y in range(8):
        for x in range(0, 8, 2):
            add_nibble(rows[y + yoff][x + xoff + 1])
            add_nibble(rows[y + yoff][x + xoff])


def gba_palette_color(palette, index):
    if index >= len(palette):
        return -1
    r, g, b = palette[index]
    return (r >> 3) + ((g >> 3) << 5) + ((b >> 3) << 10)


def main():
    _, _, palette, rows = read_png_indexed("tiles.png")

    print("//Autogenerated from tiles.png using gentiles.py")
    print('#include "tiles.h"')
    print()
    print("const unsigned short paletteData[]={")
    colors = []
    for i in range(16):
        color = gba_palette_color(palette, i)
        if color == -1:
            break
        colors.append(f"0x{color:04x}")
    print("    " + ", ".join(colors))
    print("    };\n")

    n = 0
    for y in range(1, 9 * 16, 9):
        for x in range(1, 9 * 16, 9):
            if START_TILE <= n < END_TILE:
                gen_tile(rows, x, y)
            n += 1

    print("const unsigned char tileData[]={", end="")
    for i in range(0, len(tile_data_rle), 2):
        byte = (tile_data_rle[i] << 4) | tile_data_rle[i + 1]
        if (i & 31) == 0:
            print("\n    ", end="")
        print(f"0x{byte:02x}, ", end="")
    print("    0};")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"gentiles.py: {exc}", file=sys.stderr)
        sys.exit(1)
